# Generated by Django 2.1.7 on 2019-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id_practice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('date_of_sub', models.DateField()),
            ],
            options={
                'db_table': 'practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeForGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'practice_for_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeForStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'practice_for_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskInPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=2)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'task_in_practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=45)),
                ('sername', models.CharField(max_length=45)),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=7)),
                ('variant', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
