# Generated by Django 2.1.7 on 2019-06-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id_practice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=45)),
                ('sername', models.CharField(max_length=45)),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=7)),
                ('variant', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeForGroup',
            fields=[
                ('id_practice', models.OneToOneField(db_column='id_practice', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Diploma.Practice')),
                ('date_of_sub', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'practice_for_group',
                'managed': False,
            },
        ),
    ]
