# Generated by Django 2.1.7 on 2019-05-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diploma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Practics',
            fields=[
                ('id_practice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'practics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PracticsForGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Groups')),
                ('id_practic', models.ForeignKey(db_column='id_practic', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Practics', unique=True)),
            ],
            options={
                'db_table': 'practics_for_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PracticsForStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=100)),
                ('id_practic', models.ForeignKey(db_column='id_practic', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Practics')),
            ],
            options={
                'db_table': 'practics_for_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TasksInPractics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=2)),
                ('file_name', models.CharField(max_length=100)),
                ('id_practice', models.ForeignKey(db_column='id_practice', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Practics')),
            ],
            options={
                'db_table': 'tasks_in_practics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id_theme', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'themes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('salt', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('sername', models.CharField(max_length=45)),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=7)),
                ('variant', models.CharField(blank=True, max_length=2, null=True)),
                ('group', models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Groups')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='tasksinpractics',
            name='id_theme',
            field=models.ForeignKey(db_column='id_theme', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Themes'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', on_delete=django.db.models.deletion.DO_NOTHING, to='Diploma.Users'),
        ),
    ]
