# Generated by Django 2.1.7 on 2019-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diploma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={},
        ),
    ]
