# Generated by Django 2.1.7 on 2019-06-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diploma', '0002_auto_20190619_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'managed': False},
        ),
    ]
