# Generated by Django 2.1.7 on 2019-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diploma', '0003_auto_20190619_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('path', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
    ]
